// kotListingData.ts

export interface KotOrder {
    KOTNo: string;
    orderType: string;
    customerName: string;
    customerMobile: string;
    items: string;
    status: string;
    paymentType: string;
    myAmount: string;
    tax: string;
    discount: string;
    grandTotal: string;
    created: string;
    billPrintDate: string;
    completeDuration: string;
    backgroundColor: string;
}

export const kotListingData: KotOrder[] = [
    {
        KOTNo: '01',
        orderType: 'Dine In (02) AC',
        customerName: '---',
        customerMobile: '', // Assuming customerMobile is required
        items: '3 Items',
        status: 'Active',
        paymentType: 'Card',
        myAmount: '1500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '1500.00',
        created: '2024-05-22 21:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-gray-300',
    },
    {
        KOTNo: '02',
        orderType: 'Dine In (04) Garden',
        customerName: 'Keshav Joshi +91 9878567898',
        customerMobile: '+91 9878567898',
        items: '5 Items',
        status: 'Preparing',
        paymentType: 'Other UPI',
        myAmount: '4500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '4500.00',
        created: '2024-05-22 15:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-green-500',
    },

    {
        KOTNo: '01',
        orderType: 'Dine In (02) AC',
        customerName: '---',
        customerMobile: '', // Assuming customerMobile is required
        items: '3 Items',
        status: 'Active',
        paymentType: 'Card',
        myAmount: '1500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '1500.00',
        created: '2024-05-22 21:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-gray-300',
    },
    {
        KOTNo: '02',
        orderType: 'Dine In (04) Garden',
        customerName: 'Keshav Joshi +91 9878567898',
        customerMobile: '+91 9878567898',
        items: '5 Items',
        status: 'Preparing',
        paymentType: 'Other UPI',
        myAmount: '4500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '4500.00',
        created: '2024-05-22 15:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-green-500',
    },

    {
        KOTNo: '01',
        orderType: 'Dine In (02) AC',
        customerName: '---',
        customerMobile: '', // Assuming customerMobile is required
        items: '3 Items',
        status: 'Active',
        paymentType: 'Card',
        myAmount: '1500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '1500.00',
        created: '2024-05-22 21:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-gray-300',
    },
    {
        KOTNo: '02',
        orderType: 'Dine In (04) Garden',
        customerName: 'Keshav Joshi +91 9878567898',
        customerMobile: '+91 9878567898',
        items: '5 Items',
        status: 'Preparing',
        paymentType: 'Other UPI',
        myAmount: '4500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '4500.00',
        created: '2024-05-22 15:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-green-500',
    },

    {
        KOTNo: '01',
        orderType: 'Dine In (02) AC',
        customerName: '---',
        customerMobile: '', // Assuming customerMobile is required
        items: '3 Items',
        status: 'Active',
        paymentType: 'Card',
        myAmount: '1500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '1500.00',
        created: '2024-05-22 21:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-gray-300',
    },
    {
        KOTNo: '02',
        orderType: 'Dine In (04) Garden',
        customerName: 'Keshav Joshi +91 9878567898',
        customerMobile: '+91 9878567898',
        items: '5 Items',
        status: 'Preparing',
        paymentType: 'Other UPI',
        myAmount: '4500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '4500.00',
        created: '2024-05-22 15:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-green-500',
    },

    {
        KOTNo: '01',
        orderType: 'Dine In (02) AC',
        customerName: '---',
        customerMobile: '', // Assuming customerMobile is required
        items: '3 Items',
        status: 'Active',
        paymentType: 'Card',
        myAmount: '1500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '1500.00',
        created: '2024-05-22 21:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-gray-300',
    },
    {
        KOTNo: '02',
        orderType: 'Dine In (04) Garden',
        customerName: 'Keshav Joshi +91 9878567898',
        customerMobile: '+91 9878567898',
        items: '5 Items',
        status: 'Preparing',
        paymentType: 'Other UPI',
        myAmount: '4500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '4500.00',
        created: '2024-05-22 15:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-green-500',
    },

    {
        KOTNo: '01',
        orderType: 'Dine In (02) AC',
        customerName: '---',
        customerMobile: '', // Assuming customerMobile is required
        items: '3 Items',
        status: 'Active',
        paymentType: 'Card',
        myAmount: '1500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '1500.00',
        created: '2024-05-22 21:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-gray-300',
    },
    {
        KOTNo: '02',
        orderType: 'Dine In (04) Garden',
        customerName: 'Keshav Joshi +91 9878567898',
        customerMobile: '+91 9878567898',
        items: '5 Items',
        status: 'Preparing',
        paymentType: 'Other UPI',
        myAmount: '4500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '4500.00',
        created: '2024-05-22 15:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-green-500',
    },
    {
        KOTNo: '03',
        orderType: 'Dine In (04) Garden',
        customerName: 'Keshav Joshi +91 9878567898',
        customerMobile: '+91 9878567898',
        items: '5 Items',
        status: 'Cancelled',
        paymentType: 'Other UPI',
        myAmount: '4500.00',
        tax: '0.00',
        discount: '0.00',
        grandTotal: '4500.00',
        created: '2024-05-22 15:20:51',
        billPrintDate: '--',
        completeDuration: '--',
        backgroundColor: 'bg-green-500',
    },
    // Add more orders as needed...
];
